### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by shnarg** [AltoRetrato/Oneiric-Quest#1]
Firstly - great idea! Used OQ2 (+ link cable), with a correct disc image that loads fine in Flycast. Sadly got the black screen and couldn’t play anything - log files not hugely helpful either. Is this a known issue?

**Comment by AltoRetrato** [comment]
I'm sorry for the current state of the program - it's certainly not very friendly at all, specially when dealing with errors. I'm eager to improve it, but I currently don't have enough free time to touch it at all, but I hope to in the near future.

But my first guess would be that the image was not loaded. Did you put it in `Plugins\UnrealLibretro\MyROMs\sda\sda.gdi` (with that name)? If so, please tell me the version of game and region just in case.

**Comment by AltoRetrato** [comment]
> Thank you for the reply - it’s a GUI file in that folder yes (I have ones for both game types and regions), though it’s not entirely clear from the GitHub instructions it needs to be renamed to the exact name “sda.gui”

Please note the extension should be `.gdi`, and not `.gui`. Let me know how it works for you.

**Comment by AltoRetrato** [comment]
> Just to confirm renaming the file solved the issue - thank you.

I'm glad it is working for you!

> If you can please make it all native to OQ2 in future that would save issues adjusting the height each time (both via headset and in game) to ensure controller accuracy.

Even though I think this could run natively on Quest 2, the current code is not optimized enough. It would require patching and/or rewriting major parts of the code and take a lot of time testing and debugging... and I still could not put it in the Meta Quest store (even App Lab). It would be easier to bring it to Quest 3 and SideQuest in the future, though.
